spring.application.name=demo
external.api.base-url=https://httpbin.org
external.api.username=myuser
external.api.password=mypass

token.api.base-url=https://reqres.in
token.api.email=eve.holt@reqres.in
token.api.password=cityslicka
token.api.key=free_user_3DWEFFoxbJvCQ8mMH4J43Sivwwt

server.port=${PORT:8080}